FROM python:3.12-slim

WORKDIR /bot


COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh


COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000


CMD ["./wait-for-it.sh", "fluentd:24224", "--", "python", "main.py"]